/**
 * CCL AI Fill — generates intake fields for a Client Care Letter using Azure OpenAI.
 *
 * POST /api/ccl-ai/fill
 *   Body: { matterId, practiceArea, description, clientName, opponent, enquiryNotes?, handlerName?, handlerRole? }
 *   Returns: { ok, fields: Record<string, string>, confidence, model, durationMs }
 *
 * The 26 "intake" fields that used to require manual questionnaire entry
 * are now generated by AI from matter context.
 */
const express = require('express');
const path = require('path');
const sql = require('mssql');
const { chatCompletion, chatCompletionStream, DEPLOYMENT } = require('../utils/aiClient');
const { trackEvent, trackException, trackMetric } = require('../utils/appInsights');
const { getPool } = require('../utils/db');
const { saveCclAiTrace } = require('../utils/cclPersistence');
const { resolveRequestActor } = require('../utils/requestActor');

const router = express.Router();
const CCL_PROMPT_VERSION = 'ccl-ai-v2';
const DEFAULT_CHAT_OPTIONS = {
    temperature: 0.2,
};

const ORIGINAL_CHARGES_PARAGRAPH = `I estimate the cost of the Initial Scope will be £{{figure}} plus VAT.

or

{{we_cannot_give_an_estimate_of_our_overall_charges_in_this_matter_because_reason_why_estimate_is_not_possible}}. The next stage in your matter is {{next_stage}} and we estimate that our charges up to the completion of that stage will be in the region of £{{figure_or_range}}.]`;

const ORIGINAL_DISBURSEMENTS_PARAGRAPH = `[Based on the information you have provided, we expect to incur the following disbursements:

Description | Amount | VAT chargeable
[Describe disbursement] | £[Insert estimated amount of disbursement] | [Yes OR No]
[Describe disbursement] | £[Insert estimated amount of disbursement] | [Yes OR No]
[Describe disbursement] | £[Insert estimated amount of disbursement] | [Yes OR No]

OR

We cannot give an exact figure for your disbursements, but this is likely to be in the region of £{{estimate}} {{in_total_including_vat_or_for_the_next_steps_in_your_matter}} including {{give_examples_of_what_your_estimate_includes_eg_accountants_report_and_court_fees}}.]`;

const ORIGINAL_COSTS_OTHER_PARTY_PARAGRAPH = `We do not expect that you will have to pay another party's costs. This only tends to arise in litigation and is therefore not relevant to your matter.

OR

There is a risk that you may have to pay {{identify_the_other_party_eg_your_opponents}} costs in this matter. This is explained in section 5, Funding and billing below.`;

// ─── Practice area defaults (fallback if AI fails) ─────────────────────────
const PRACTICE_AREA_DEFAULTS = {
    commercial: {
        insert_current_position_and_scope_of_retainer: 'We will review the relevant documentation, advise you on your legal position, and take such steps as are agreed to protect your commercial interests.',
        next_steps: 'review the documents you have provided and advise on the merits of your position',
        realistic_timescale: '4-6 weeks for initial advice',
        next_stage: 'document review and initial advice',
        charges_estimate_paragraph: ORIGINAL_CHARGES_PARAGRAPH,
        disbursements_paragraph: ORIGINAL_DISBURSEMENTS_PARAGRAPH,
        costs_other_party_paragraph: ORIGINAL_COSTS_OTHER_PARTY_PARAGRAPH,
        figure: '2,500',
        figure_or_range: '2,500 - 5,000',
        estimate: '£2,500 to £5,000 plus VAT',
        and_or_intervals_eg_every_three_months: 'monthly',
        insert_next_step_you_would_like_client_to_take: 'Provide all relevant contractual documentation',
        state_why_this_step_is_important: 'We cannot advise properly without sight of the key documents',
        insert_consequence: 'we will be unable to progress your matter',
        state_amount: '2,500',
        describe_first_document_or_information_you_need_from_your_client: 'Copy of the relevant contract or agreement',
        describe_second_document_or_information_you_need_from_your_client: 'All relevant correspondence with the other party',
        describe_third_document_or_information_you_need_from_your_client: 'Any supporting invoices, payment records, or evidence',
    },
    property: {
        insert_current_position_and_scope_of_retainer: 'We will act on your behalf in connection with the property transaction, dealing with all necessary legal formalities through to completion.',
        next_steps: 'review the title documentation and raise any necessary enquiries',
        realistic_timescale: '8-12 weeks to completion',
        next_stage: 'title review and pre-contract enquiries',
        charges_estimate_paragraph: ORIGINAL_CHARGES_PARAGRAPH,
        disbursements_paragraph: ORIGINAL_DISBURSEMENTS_PARAGRAPH,
        costs_other_party_paragraph: ORIGINAL_COSTS_OTHER_PARTY_PARAGRAPH,
        figure: '1,500',
        figure_or_range: '1,500 - 3,000',
        estimate: '£1,500 to £3,000 plus VAT',
        and_or_intervals_eg_every_three_months: 'on completion',
        insert_next_step_you_would_like_client_to_take: 'Complete and return the property information questionnaire',
        state_why_this_step_is_important: 'We need this information to prepare the contract pack',
        insert_consequence: 'there may be delays in progressing the transaction',
        state_amount: '1,500',
        describe_first_document_or_information_you_need_from_your_client: 'Title deeds or Land Registry documents',
        describe_second_document_or_information_you_need_from_your_client: 'Proof of identity and address',
        describe_third_document_or_information_you_need_from_your_client: 'Mortgage offer (if applicable)',
    },
    employment: {
        insert_current_position_and_scope_of_retainer: 'We will review the circumstances of your employment matter, advise you on your legal position and rights, and take such steps as are agreed to protect your interests.',
        next_steps: 'review the documents you have provided and advise on your position and options',
        realistic_timescale: '2-4 weeks for initial advice',
        next_stage: 'document review and initial advice on merits',
        charges_estimate_paragraph: ORIGINAL_CHARGES_PARAGRAPH,
        disbursements_paragraph: ORIGINAL_DISBURSEMENTS_PARAGRAPH,
        costs_other_party_paragraph: ORIGINAL_COSTS_OTHER_PARTY_PARAGRAPH,
        figure: '1,500',
        figure_or_range: '1,500 - 3,000',
        estimate: '£1,500 to £3,000 plus VAT',
        and_or_intervals_eg_every_three_months: 'monthly',
        insert_next_step_you_would_like_client_to_take: 'Provide copies of your employment contract and any relevant correspondence',
        state_why_this_step_is_important: 'We need to understand the full contractual position before advising',
        insert_consequence: 'we will be unable to advise you properly',
        state_amount: '1,500',
        describe_first_document_or_information_you_need_from_your_client: 'Employment contract and any amendments',
        describe_second_document_or_information_you_need_from_your_client: 'Relevant correspondence (grievances, disciplinary letters, etc.)',
        describe_third_document_or_information_you_need_from_your_client: 'Any other supporting documentation',
    },
    construction: {
        insert_current_position_and_scope_of_retainer: 'We will review the construction dispute, advise on your contractual and statutory rights, and take such steps as are agreed to resolve the matter.',
        next_steps: 'review the contract and associated documents, and advise on the merits of your position',
        realistic_timescale: '4-8 weeks for initial advice',
        next_stage: 'contract review and initial advice',
        charges_estimate_paragraph: ORIGINAL_CHARGES_PARAGRAPH,
        disbursements_paragraph: ORIGINAL_DISBURSEMENTS_PARAGRAPH,
        costs_other_party_paragraph: ORIGINAL_COSTS_OTHER_PARTY_PARAGRAPH,
        figure: '3,000',
        figure_or_range: '3,000 - 7,500',
        estimate: '£3,000 to £7,500 plus VAT',
        and_or_intervals_eg_every_three_months: 'monthly',
        insert_next_step_you_would_like_client_to_take: 'Provide all relevant contractual documentation and correspondence',
        state_why_this_step_is_important: 'Construction disputes are document-intensive and we need the full picture',
        insert_consequence: 'we may not be able to assess the merits of your claim',
        state_amount: '3,000',
        describe_first_document_or_information_you_need_from_your_client: 'The building contract and any variations',
        describe_second_document_or_information_you_need_from_your_client: 'Relevant correspondence, including any notices served',
        describe_third_document_or_information_you_need_from_your_client: 'Photographs, surveys, or expert reports (if available)',
    },
    'dispute-resolution': {
        insert_current_position_and_scope_of_retainer: 'We will review the circumstances of your dispute, advise on the merits and available resolution options, and take such steps as are agreed.',
        next_steps: 'review the documents you have provided and advise on the strengths of your position',
        realistic_timescale: '4-6 weeks for initial advice',
        next_stage: 'document review and merits assessment',
        charges_estimate_paragraph: ORIGINAL_CHARGES_PARAGRAPH,
        disbursements_paragraph: ORIGINAL_DISBURSEMENTS_PARAGRAPH,
        costs_other_party_paragraph: ORIGINAL_COSTS_OTHER_PARTY_PARAGRAPH,
        figure: '2,000',
        figure_or_range: '2,000 - 5,000',
        estimate: '£2,000 to £5,000 plus VAT',
        and_or_intervals_eg_every_three_months: 'monthly',
        insert_next_step_you_would_like_client_to_take: 'Provide all relevant documentation and a chronology of events',
        state_why_this_step_is_important: 'We need to understand the full factual background before advising',
        insert_consequence: 'we will be unable to properly assess the merits of your case',
        state_amount: '2,000',
        describe_first_document_or_information_you_need_from_your_client: 'The relevant contracts or agreements',
        describe_second_document_or_information_you_need_from_your_client: 'All correspondence with the other party',
        describe_third_document_or_information_you_need_from_your_client: 'Any evidence supporting your position (invoices, photographs, etc.)',
    },
};

// ─── System prompt ─────────────────────────────────────────────────────────
const SYSTEM_PROMPT = `You are a senior UK solicitor at Helix Law, a specialist litigation firm. Helix Law acts across four core practice areas: commercial disputes (shareholder and partnership disputes, investment and loan disputes, debt recovery, statutory demands, civil fraud, contract disputes, restrictive covenants, injunctions), property disputes (landlord and tenant, evictions, boundary and land disputes), construction disputes (adjudication, payment disputes, contract breaches, unlawful terminations), and employment law. The firm is SRA-regulated (ID 565557) and based in Brighton. Your task is to generate the intake fields for a Client Care Letter (CCL) based on the matter context provided.

The CCL is a regulatory requirement under SRA rules. It must be professional, accurate, and tailored to the specific matter. Write in clear, professional British English suitable for a client who is not legally trained.

CRITICAL: You are filling in the placeholder fields of a REAL legal template. Each field you generate is injected verbatim into the letter — it MUST read naturally in context. Below is how each field appears in the actual template so you understand exactly where your output goes.

TEMPLATE CONTEXT (how your fields are used — {{field_name}} = your output):

Section 2 — Scope of services:
"{{insert_current_position_and_scope_of_retainer}} ("Initial Scope")"
→ This is the opening paragraph of the scope section. Write 2-4 complete sentences describing what the client has instructed Helix Law to do. Must be specific to this matter. Ends with the text ("Initial Scope") which is added by the template.

Section 3 — Next steps:
"The next steps in your matter are {{next_steps}}."
→ Start lowercase. This completes the sentence. List 2-3 specific actions.

"We expect this will take {{realistic_timescale}}."
→ A realistic period, e.g. "4-6 weeks" or "2-3 months".

Section 4.1 — Charges:
"My rate is £{{handler_hourly_rate}} per hour."
→ Number only (already auto-filled, but if missing use the rate given in context).

"{{charges_estimate_paragraph}}"
→ Use one of these two alternatives VERBATIM (do not rephrase):
  IF an estimate IS possible: "I estimate the cost of the Initial Scope will be in the region of £[amount or range] plus VAT." (replace [amount or range] with real figures).
  IF an estimate is NOT possible: "[We cannot give an estimate of our overall charges in this matter because [reason]]. The next stage in your matter is [next stage] and we estimate that our charges up to the completion of that stage will be in the region of £[figure or range]." (fill in the bracketed parts).
→ SOURCING RULE: If Deal Amount exists, build the estimate around it (e.g. if deal is £3,000, write "in the region of £3,000 plus VAT"). If Pitch Email quoted a range, use that range verbatim. Only fall back to practice area norms if no financial data exists.

Section 4.2 — Disbursements:
"{{disbursements_paragraph}}"
→ Use one of these two alternatives VERBATIM (do not rephrase):
  IF specific disbursements are known: "Based on the information you have provided, we expect to incur the following disbursements: [list the disbursements with estimated amounts and whether VAT is chargeable]."
  IF exact figures are not possible: "We cannot give an exact figure for your disbursements, but this is likely to be in the region of £[estimate] [in total, including VAT / for the next steps in your matter] including [give examples, e.g. court fees and barrister fees]." (fill in the bracketed parts based on the matter type).

Section 4.3 — Costs other party:
"{{costs_other_party_paragraph}}"
→ Use one of these two alternatives VERBATIM (do not rephrase):
  IF NOT litigation / no opponent: "We do not expect that you will have to pay another party's costs. This only tends to arise in litigation and is therefore not relevant to your matter."
  IF litigation / opponent exists: "There is a risk that you may have to pay [opponent name]'s costs in this matter. This is explained in section 5, Funding and billing below." (replace [opponent name] with the actual opponent).

Section 6 — Payment on account:
"Please provide us with £{{figure}} on account of costs."
→ Number only, no £ sign, e.g. "2,500".
→ SOURCING RULE: If a Deal Amount is provided, use it directly as the payment on account (the deal amount IS the agreed fee). If a Pitch Amount is provided but no Deal Amount, use the pitch amount. If NEITHER exists, use the low end of a conservative practice-area estimate. NEVER invent a figure that contradicts an agreed amount.

Section 7 — Costs updates:
"We have agreed to provide you with an update on the amount of costs when appropriate as the matter progresses{{and_or_intervals_eg_every_three_months}}."
→ Starts with a space or ", " then the interval. Usually " monthly" or " every three months".

Section 13 — Duties to court:
"Your matter {{may_will}} involve court proceedings."
→ Either "may" or "will". Use "may" unless court proceedings are certain.

Section 18 — Action points:
"☐ {{insert_next_step_you_would_like_client_to_take}} | {{state_why_this_step_is_important}}"
→ insert_next_step: Imperative sentence — what the client must do. Be specific to this matter.
→ state_why_this_step_is_important: Why it matters. 1 sentence.

"☐ Provide a payment on account of costs and disbursements of £{{state_amount}} | If we do not receive a payment on account... {{insert_consequence}}"
→ state_amount: Same as figure.
→ insert_consequence: What happens if they don't pay. Default wording: "there may be a delay in starting work on your behalf"

"{{describe_first_document_or_information_you_need_from_your_client}}"
"{{describe_second_document_or_information_you_need_from_your_client}}"
"{{describe_third_document_or_information_you_need_from_your_client}}"
→ Each is a bullet point. Be specific to this matter type — name the actual documents needed.

NOT IN TEMPLATE (metadata fields):
- "next_stage": Brief label for the next milestone (used for internal tracking, not shown to client)
- "figure_or_range": Cost estimate range, e.g. "2,500 - 5,000" (used in sidebar display)
- "estimate": Full estimate string, e.g. "£2,500 to £5,000 plus VAT"
- "in_total_including_vat_or_for_the_next_steps_in_your_matter": Either "in total, including VAT" or "for the next steps in your matter"
- "give_examples_of_what_your_estimate_includes_eg_accountants_report_and_court_fees": Brief list of what the estimate covers
- "we_cannot_give_an_estimate_of_our_overall_charges_in_this_matter_because_reason_why_estimate_is_not_possible": If estimate IS possible, set to "". Only fill if genuinely impossible.
- "simple_disbursements_estimate": Estimated disbursements (number only, e.g. "500")

COST ACCURACY RULES:
1. If a Deal Amount is provided, it IS the agreed fee — the payment on account (figure) should equal it. The charges_estimate_paragraph must be consistent with the deal amount. Do NOT apply arbitrary percentages (no "50-100% of the low end").
2. If a Pitch Email is provided, the client has already seen those numbers — match them exactly for charges_estimate_paragraph and figure.
3. If NEITHER deal amount NOR pitch amount exists, the costs fields are LOW CONFIDENCE — use practice area norms but mark clearly that these are estimates pending fee earner confirmation.
4. Never invent costs figures that contradict agreed amounts. If the deal says £3,000 and you output £1,500, that is wrong.
5. state_amount MUST always equal figure — they are the same value shown in different template locations.

Respond with ONLY a JSON object containing these fields. No markdown, no explanation, just the JSON object.`;

// ─── Gather full workbench context from all sources ────────────────────────

function getInternalBase() {
    const port = process.env.PORT || 8080;
    const isNamedPipe = typeof port === 'string' && port.startsWith('\\\\.\\pipe\\');
    return isNamedPipe && process.env.WEBSITE_HOSTNAME
        ? `https://${process.env.WEBSITE_HOSTNAME}`
        : `http://localhost:${port}`;
}

async function fetchJson(url) {
    try {
        const resp = await fetch(url);
        if (!resp.ok) return null;
        return await resp.json();
    } catch { return null; }
}

async function getTableColumns(pool, tableName) {
    const result = await pool.request()
        .input('tableName', sql.NVarChar(128), tableName)
        .query(`
            SELECT COLUMN_NAME
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = @tableName
        `);
    return new Set((result.recordset || []).map((row) => String(row.COLUMN_NAME || '').trim()).filter(Boolean));
}

function resolveOrderBy(columns, candidates) {
    for (const candidate of candidates) {
        if (columns.has(candidate)) return candidate;
    }
    return null;
}

function buildDebugContext(fullContext, contextSources) {
    const makeSnippet = (value, limit = 350) => {
        const text = String(value || '').trim();
        if (!text) return '';
        return text.length > limit ? `${text.slice(0, limit)}…` : text;
    };

    return {
        contextFields: {
            practiceArea: fullContext.practiceArea || '',
            typeOfWork: fullContext.typeOfWork || '',
            clientName: fullContext.clientName || '',
            opponent: fullContext.opponent || '',
            handlerName: fullContext.handlerName || '',
            handlerRole: fullContext.handlerRole || '',
            handlerRate: fullContext.handlerRate || '',
            dealAmount: fullContext.dealAmount || '',
            pitchAmount: fullContext.pitchAmount || '',
            enquiryValue: fullContext.enquiryValue || '',
            instructionStage: fullContext.instructionStage || '',
            company: fullContext.company || '',
            clientType: fullContext.clientType || '',
            source: fullContext.source || '',
        },
        sourceCount: contextSources.length,
        sources: contextSources,
        snippets: {
            initialCallNotes: makeSnippet(fullContext.initialCallNotes),
            enquiryNotes: makeSnippet(fullContext.enquiryNotes),
            instructionNotes: makeSnippet(fullContext.instructionNotes),
            dealServiceDescription: makeSnippet(fullContext.dealServiceDescription),
            pitchServiceDescription: makeSnippet(fullContext.pitchServiceDescription),
            pitchEmailBody: makeSnippet(fullContext.pitchEmailBody),
            callTranscripts: makeSnippet(fullContext.callTranscripts, 450),
        },
    };
}

function formatFallbackReason(errorMessage) {
    const message = String(errorMessage || '').trim();
    if (!message) return 'Unknown AI error';
    const lower = message.toLowerCase();
    if (lower.includes('deployment') && lower.includes('does not exist')) {
        return `Azure OpenAI deployment '${DEPLOYMENT}' is not available for this resource. Check AZURE_OPENAI_DEPLOYMENT and Azure deployment naming.`;
    }
    return message;
}

async function gatherFullContext(matterId, instructionRef) {
    const context = {};
    const base = getInternalBase();
    const instrConnStr = process.env.INSTRUCTIONS_SQL_CONNECTION_STRING;
    const coreConnStr = process.env.SQL_CONNECTION_STRING;

    // ── 1. Resolve InstructionRef + ProspectId from Instructions DB ──
    // The frontend may pass an HLX-format instructionRef directly (preferred)
    // or a Clio displayNumber as matterId (fallback).
    let resolvedInstructionRef = instructionRef || null;
    let prospectId = null;
    let phone = null;

    if (instrConnStr) {
        try {
            const pool = await getPool(instrConnStr);
            const instructionsColumns = await getTableColumns(pool, 'Instructions');
            const instructionsOrderBy = resolveOrderBy(instructionsColumns, ['CreatedAt', 'UpdatedAt', 'InstructionDateTime', 'InstructionRef']);
            const instructionsProspectColumn = resolveOrderBy(instructionsColumns, ['ProspectId', 'prospectId', 'id', 'acid']);

            const pitchContentColumns = await getTableColumns(pool, 'PitchContent');
            const pitchOrderBy = resolveOrderBy(pitchContentColumns, ['CreatedAt', 'UpdatedAt', 'PitchId', 'Id']);

            const instructionsOrderClause = instructionsOrderBy ? `ORDER BY ${instructionsOrderBy} DESC` : '';
            const pitchOrderClause = pitchOrderBy ? `ORDER BY ${pitchOrderBy} DESC` : '';

            const instructionSelectParts = [
                'InstructionRef',
                instructionsProspectColumn ? `${instructionsProspectColumn} AS ProspectId` : `NULL AS ProspectId`,
                'Stage', 'FirstName', 'LastName',
                'Notes', 'Phone', 'Email', 'CompanyName', 'HelixContact',
                'Title', 'Gender', 'ClientType',
            ];

            // Build WHERE clause — prefer exact InstructionRef match, fall back to matterId
            const whereParts = [];
            const inputParams = [];
            if (resolvedInstructionRef) {
                whereParts.push("InstructionRef = @InstructionRef");
                inputParams.push({ name: 'InstructionRef', type: sql.NVarChar(100), value: resolvedInstructionRef });
            }
            // Also try matterId patterns as fallback
            whereParts.push("InstructionRef LIKE '%' + @MatterId + '%'");
            inputParams.push({ name: 'MatterId', type: sql.NVarChar(100), value: matterId });
            if (instructionsProspectColumn) {
                whereParts.push(`${instructionsProspectColumn} = @MatterId`);
            }

            const request = pool.request();
            for (const param of inputParams) {
                request.input(param.name, param.type, param.value);
            }

            // Try matching by matter ID patterns
            const instrResult = await request
                .query(`SELECT TOP 1 
                    ${instructionSelectParts.join(',\n                    ')}
                FROM Instructions
                WHERE ${whereParts.join('\n                   OR ')}
                     ${instructionsOrderClause}`);

            if (instrResult.recordset.length > 0) {
                const row = instrResult.recordset[0];
                resolvedInstructionRef = row.InstructionRef;
                prospectId = row.ProspectId;
                phone = row.Phone;
                context.instructionNotes = row.Notes || '';
                context.instructionStage = row.Stage || '';
                context.clientType = row.ClientType || '';
                context.companyName = row.CompanyName || '';
                context.prospectEmail = row.Email || '';
                context.feeEarnerEmail = row.HelixContact || '';
                if (row.Gender) context.clientGender = row.Gender;
            }

            // Get deal data (service description, amount, pitch info)
            if (resolvedInstructionRef) {
                const dealResult = await pool.request()
                    .input('InstructionRef', sql.NVarChar(100), resolvedInstructionRef)
                    .query(`SELECT TOP 1
                        ServiceDescription, Amount, Status, PitchedBy,
                        CloseDate, PitchValidUntil
                    FROM Deals
                    WHERE InstructionRef = @InstructionRef
                    ORDER BY DealId DESC`);

                if (dealResult.recordset.length > 0) {
                    const deal = dealResult.recordset[0];
                    context.dealServiceDescription = deal.ServiceDescription || '';
                    context.dealAmount = deal.Amount ? String(deal.Amount) : '';
                    context.dealPitchedBy = deal.PitchedBy || '';
                }
            }

            // Get pitch content (the actual email sent to the client)
            if (resolvedInstructionRef) {
                const pitchResult = await pool.request()
                    .input('InstructionRef', sql.NVarChar(100), resolvedInstructionRef)
                    .query(`SELECT TOP 1
                        EmailSubject, EmailBody, Amount, ServiceDescription, Notes
                    FROM PitchContent
                    WHERE InstructionRef = @InstructionRef
                    ${pitchOrderClause}`);

                if (pitchResult.recordset.length > 0) {
                    const pitch = pitchResult.recordset[0];
                    context.pitchEmailBody = pitch.EmailBody || '';
                    context.pitchServiceDescription = pitch.ServiceDescription || '';
                    context.pitchAmount = pitch.Amount ? String(pitch.Amount) : '';
                    context.pitchNotes = pitch.Notes || '';
                }
            }
        } catch (err) {
            console.warn('[CCL-AI] Instructions DB lookup failed:', err.message);
        }
    }

    // ── 2. Core Data enquiry (initial call notes — often the richest text) ──
    // If we don't have a prospectId from Instructions DB, try to find it via
    // the matters table using the Clio displayNumber.
    if (coreConnStr && !prospectId) {
        try {
            const pool = await getPool(coreConnStr);
            const mattersResult = await pool.request()
                .input('DisplayNumber', sql.NVarChar(100), matterId)
                .query(`SELECT TOP 1 [Client Name], [Unique ID], [Display Number]
                    FROM matters
                    WHERE [Display Number] = @DisplayNumber`);

            if (mattersResult.recordset.length > 0) {
                const matterRow = mattersResult.recordset[0];
                const clientName = matterRow['Client Name'] || '';
                // Try to find the enquiry by client name
                if (clientName) {
                    const nameParts = clientName.trim().split(/\s+/);
                    const firstName = nameParts[0] || '';
                    const lastName = nameParts.slice(1).join(' ') || '';
                    if (firstName && lastName) {
                        const enqResult = await pool.request()
                            .input('FirstName', sql.NVarChar(100), firstName)
                            .input('LastName', sql.NVarChar(100), lastName)
                            .query(`SELECT TOP 1 ID
                                FROM enquiries
                                WHERE First_Name = @FirstName AND Last_Name = @LastName
                                ORDER BY ID DESC`);
                        if (enqResult.recordset.length > 0) {
                            prospectId = enqResult.recordset[0].ID;
                        }
                    }
                }
            }
        } catch (err) {
            console.warn('[CCL-AI] Matters cross-reference lookup failed:', err.message);
        }
    }

    if (coreConnStr && prospectId) {
        try {
            const pool = await getPool(coreConnStr);
            const result = await pool.request()
                .input('ProspectId', sql.Int, Number(prospectId))
                .query(`SELECT TOP 1
                    First_Name, Last_Name, Email, Phone_Number,
                    Area_of_Work, [Type of Work], Company, 
                    [Initial_first_call_notes], Notes, Source,
                    [Additional Information], Value, Rating,
                    [Point_of_Contact], [Method_of_Contact]
                FROM enquiries
                WHERE ID = @ProspectId
                ORDER BY ID DESC`);

            if (result.recordset.length > 0) {
                const row = result.recordset[0];
                // Initial call notes are usually the richest source
                context.initialCallNotes = row.Initial_first_call_notes || '';
                context.enquiryNotes = row.Notes || row['Additional Information'] || '';
                context.areaOfWork = row.Area_of_Work || '';
                context.typeOfWork = row['Type of Work'] || '';
                context.source = row.Source || '';
                context.company = row.Company || context.companyName || '';
                context.enquiryValue = row.Value ? String(row.Value) : '';
                context.methodOfContact = row.Method_of_Contact || '';
                if (!phone) phone = row.Phone_Number;
            }
        } catch (err) {
            console.warn('[CCL-AI] Core Data enquiry lookup failed:', err.message);
        }
    }

    // ── 3. CallRail transcripts (if we have a phone number) ──
    if (phone) {
        try {
            // CallRail endpoint is POST, so use fetch directly
            const resp = await fetch(`${base}/api/callrailCalls`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ phoneNumber: phone, maxResults: 5 }),
            });
            if (resp.ok) {
                const calls = await resp.json();
                const transcripts = (Array.isArray(calls) ? calls : calls.calls || [])
                    .filter(c => c.transcription || c.note)
                    .slice(0, 3) // limit to 3 most recent for token budget
                    .map(c => {
                        const parts = [];
                        if (c.startTime) parts.push(`[${new Date(c.startTime).toLocaleDateString('en-GB')}]`);
                        if (c.direction) parts.push(`(${c.direction})`);
                        if (c.duration) parts.push(`${Math.round(c.duration / 60)}min`);
                        if (c.note) parts.push(`Notes: ${c.note}`);
                        if (c.transcription) parts.push(`Transcript: ${c.transcription.substring(0, 1500)}`);
                        return parts.join(' ');
                    });
                if (transcripts.length > 0) {
                    context.callTranscripts = transcripts.join('\n---\n');
                }
            }
        } catch (err) {
            console.warn('[CCL-AI] CallRail lookup failed:', err.message);
        }
    }

    // ── 4. Pitch emails (from pitches endpoint using ProspectId) ──
    if (prospectId && !context.pitchEmailBody) {
        try {
            const pitchData = await fetchJson(`${base}/api/pitches/${prospectId}`);
            if (pitchData && Array.isArray(pitchData) && pitchData.length > 0) {
                const latest = pitchData[0];
                context.pitchEmailBody = context.pitchEmailBody || latest.EmailBody || '';
                context.pitchServiceDescription = context.pitchServiceDescription || latest.ServiceDescription || '';
                context.pitchAmount = context.pitchAmount || (latest.Amount ? String(latest.Amount) : '');
            }
        } catch (err) {
            console.warn('[CCL-AI] Pitches lookup failed:', err.message);
        }
    }

    // Expose contact details so pressure test can fetch emails/calls
    if (phone) context.phone = phone;

    return context;
}

// ─── Build user prompt from all available context ──────────────────────────
function buildUserPrompt(data) {
    const parts = [];

    // Core matter details
    parts.push(`MATTER CONTEXT:`);
    parts.push(`- Practice Area: ${data.practiceArea || data.areaOfWork || 'General'}`);
    if (data.typeOfWork) parts.push(`- Type of Work: ${data.typeOfWork}`);
    parts.push(`- Client Name: ${data.clientName || 'Not specified'}`);
    parts.push(`- Matter Description: ${data.description || 'Not specified'}`);
    if (data.opponent) parts.push(`- Opposing Party: ${data.opponent}`);
    if (data.handlerName) parts.push(`- Handler: ${data.handlerName} (${data.handlerRole || 'Solicitor'})`);
    if (data.handlerRate) parts.push(`- Handler Hourly Rate: £${data.handlerRate}`);
    if (data.company) parts.push(`- Client Company: ${data.company}`);
    if (data.clientType) parts.push(`- Client Type: ${data.clientType}`);
    if (data.clientGender) parts.push(`- Client Gender: ${data.clientGender}`);
    if (data.enquiryValue) parts.push(`- Enquiry Value: £${data.enquiryValue}`);
    if (data.source) parts.push(`- Enquiry Source: ${data.source}`);
    if (data.instructionStage) parts.push(`- Instruction Stage: ${data.instructionStage}`);

    // Deal data (what was pitched and agreed)
    if (data.dealServiceDescription || data.dealAmount) {
        parts.push(`\nDEAL INFORMATION:`);
        if (data.dealServiceDescription) parts.push(`Service: ${data.dealServiceDescription}`);
        if (data.dealAmount) parts.push(`Agreed Amount: £${data.dealAmount}`);
        if (data.dealPitchedBy) parts.push(`Pitched By: ${data.dealPitchedBy}`);
    }

    // Pitch email (what the client was actually told)
    if (data.pitchEmailBody) {
        parts.push(`\nPITCH EMAIL SENT TO CLIENT (use this to match scope and costs):`);
        parts.push(data.pitchEmailBody.substring(0, 3000));
    } else if (data.pitchServiceDescription) {
        parts.push(`\nPITCH SERVICE DESCRIPTION: ${data.pitchServiceDescription}`);
        if (data.pitchAmount) parts.push(`Pitch Amount: £${data.pitchAmount}`);
    }

    // Initial call notes (often the richest text)
    if (data.initialCallNotes) {
        parts.push(`\nINITIAL CALL NOTES (first contact with client):`);
        parts.push(data.initialCallNotes.substring(0, 3000));
    }

    // Enquiry notes
    if (data.enquiryNotes && data.enquiryNotes !== data.initialCallNotes) {
        parts.push(`\nENQUIRY NOTES:`);
        parts.push(data.enquiryNotes.substring(0, 2000));
    }

    // Instruction notes
    if (data.instructionNotes) {
        parts.push(`\nINSTRUCTION NOTES:`);
        parts.push(data.instructionNotes.substring(0, 2000));
    }

    // Call transcripts
    if (data.callTranscripts) {
        parts.push(`\nCALL TRANSCRIPTS (conversations with client):`);
        parts.push(data.callTranscripts.substring(0, 4000));
    }

    // Pitch notes
    if (data.pitchNotes) {
        parts.push(`\nPITCH NOTES: ${data.pitchNotes.substring(0, 1000)}`);
    }

    parts.push(`\nGenerate all CCL intake fields for this matter. Be specific and tailored — the client should read this letter and feel it was written specifically for their situation. Use the pitch email and deal amounts to match the costs figures. Use the call transcripts and notes to understand what the client actually needs.`);

    return parts.join('\n');
}

// ─── Summarise what data sources were used (for prompt transparency) ───────
function summariseContextSources(dbContext) {
    const sources = [];
    if (dbContext.initialCallNotes) sources.push('Initial call notes');
    if (dbContext.enquiryNotes) sources.push('Enquiry notes');
    if (dbContext.instructionNotes) sources.push('Instruction notes');
    if (dbContext.pitchEmailBody) sources.push('Pitch email');
    if (dbContext.pitchServiceDescription) sources.push('Pitch service description');
    if (dbContext.dealServiceDescription) sources.push('Deal information');
    if (dbContext.callTranscripts) sources.push('Call transcripts');
    if (dbContext.areaOfWork) sources.push('Area of work classification');
    if (dbContext.typeOfWork) sources.push('Type of work');
    if (dbContext.company) sources.push('Company details');
    return sources;
}

async function buildCclContextPackage({
    matterId,
    instructionRef,
    practiceArea,
    description,
    clientName,
    opponent,
    enquiryNotes,
    handlerName,
    handlerRole,
    handlerRate,
}) {
    const dbContext = await gatherFullContext(matterId, instructionRef);
    const fullContext = {
        practiceArea: practiceArea || dbContext.areaOfWork || '',
        typeOfWork: dbContext.typeOfWork || '',
        description,
        clientName,
        opponent,
        handlerName,
        handlerRole,
        handlerRate,
        clientType: dbContext.clientType || '',
        clientGender: dbContext.clientGender || '',
        company: dbContext.company || '',
        source: dbContext.source || '',
        enquiryValue: dbContext.enquiryValue || '',
        instructionStage: dbContext.instructionStage || '',
        initialCallNotes: dbContext.initialCallNotes || '',
        enquiryNotes: enquiryNotes || dbContext.enquiryNotes || '',
        instructionNotes: dbContext.instructionNotes || '',
        dealServiceDescription: dbContext.dealServiceDescription || '',
        dealAmount: dbContext.dealAmount || '',
        dealPitchedBy: dbContext.dealPitchedBy || '',
        pitchEmailBody: dbContext.pitchEmailBody || '',
        pitchServiceDescription: dbContext.pitchServiceDescription || '',
        pitchAmount: dbContext.pitchAmount || '',
        pitchNotes: dbContext.pitchNotes || '',
        callTranscripts: dbContext.callTranscripts || '',
    };

    const userPrompt = buildUserPrompt(fullContext);
    const contextSources = summariseContextSources(dbContext);
    const debugContext = buildDebugContext(fullContext, contextSources);

    return {
        dbContext,
        fullContext,
        userPrompt,
        contextSources,
        debugContext,
        systemPrompt: SYSTEM_PROMPT,
        systemPromptLength: SYSTEM_PROMPT.length,
        promptVersion: CCL_PROMPT_VERSION,
    };
}

async function previewCclContext(input) {
    const contextPackage = await buildCclContextPackage(input);
    return {
        ok: true,
        dataSources: contextPackage.contextSources,
        contextFields: contextPackage.debugContext.contextFields,
        snippets: contextPackage.debugContext.snippets,
        userPrompt: contextPackage.userPrompt,
        userPromptLength: contextPackage.userPrompt.length,
        systemPromptLength: contextPackage.systemPromptLength,
        promptVersion: contextPackage.promptVersion,
    };
}

async function runCclAiFill(input, actor = 'system') {
    const {
        matterId,
        practiceArea,
        clientName,
        opponent,
    } = input || {};

    const trackingId = Math.random().toString(36).slice(2, 10);
    const startMs = Date.now();
    const chatOptions = { ...DEFAULT_CHAT_OPTIONS };

    trackEvent('CCL.AiFill.Started', {
        trackingId,
        matterId: String(matterId),
        practiceArea: practiceArea || 'unknown',
        deployment: DEPLOYMENT,
    });

    try {
        const contextPackage = await buildCclContextPackage(input);
        const aiFields = await chatCompletion(SYSTEM_PROMPT, contextPackage.userPrompt, chatOptions);
        const durationMs = Date.now() - startMs;

        const expectedKeys = [
            'insert_current_position_and_scope_of_retainer',
            'next_steps',
            'charges_estimate_paragraph',
        ];
        const hasCore = expectedKeys.every(k => aiFields[k] && aiFields[k].length > 10);

        if (!hasCore || aiFields._parseError) {
            const paKey = normalisePracticeArea(practiceArea);
            const defaults = PRACTICE_AREA_DEFAULTS[paKey] || PRACTICE_AREA_DEFAULTS['commercial'];
            const merged = { ...defaults, ...stripEmpty(aiFields) };

            trackEvent('CCL.AiFill.PartialFallback', {
                trackingId, matterId: String(matterId), practiceArea: paKey, durationMs: String(durationMs),
            });

            let aiTraceId = null;
            try {
                aiTraceId = await saveCclAiTrace({
                    matterId, trackingId, aiStatus: 'partial', model: DEPLOYMENT, durationMs,
                    temperature: chatOptions.temperature,
                    systemPrompt: SYSTEM_PROMPT, userPrompt: contextPackage.userPrompt, userPromptLength: contextPackage.userPrompt.length,
                    aiOutputJson: stripEmpty(aiFields), generatedFieldCount: Object.keys(stripEmpty(aiFields)).length,
                    confidence: 'partial', dataSourcesJson: contextPackage.contextSources,
                    contextFieldsJson: contextPackage.debugContext.contextFields, contextSnippetsJson: contextPackage.debugContext.snippets,
                    fallbackReason: 'AI response was incomplete or unparsable; merged with defaults.',
                    createdBy: actor,
                });
            } catch (err) {
                console.warn('[CCL-AI] Trace persist failed:', err.message);
            }

            return {
                ok: true,
                fields: merged,
                confidence: 'partial',
                model: DEPLOYMENT,
                durationMs,
                source: 'ai+defaults',
                dataSources: contextPackage.contextSources,
                contextSummary: `Used ${contextPackage.contextSources.length} data source(s): ${contextPackage.contextSources.join(', ')}`,
                userPrompt: contextPackage.userPrompt,
                systemPrompt: SYSTEM_PROMPT,
                fallbackReason: 'AI response was incomplete or unparsable; merged with defaults.',
                promptVersion: contextPackage.promptVersion,
                aiTraceId,
                debug: {
                    trackingId,
                    deployment: DEPLOYMENT,
                    aiStatus: 'partial',
                    options: chatOptions,
                    userPromptLength: contextPackage.userPrompt.length,
                    generatedFieldCount: Object.keys(stripEmpty(aiFields)).length,
                    context: contextPackage.debugContext,
                },
            };
        }

        trackEvent('CCL.AiFill.Completed', {
            trackingId,
            matterId: String(matterId),
            practiceArea: practiceArea || 'unknown',
            durationMs: String(durationMs),
            fieldCount: String(Object.keys(aiFields).length),
            filledFieldCount: String(Object.keys(stripEmpty(aiFields)).length),
        });
        trackMetric('CCL.AiFill.Duration', durationMs, { practiceArea: practiceArea || 'unknown' });
        trackMetric('CCL.AiFill.FieldCount', Object.keys(stripEmpty(aiFields)).length, { practiceArea: practiceArea || 'unknown' });
        trackMetric('CCL.AiFill.ContextSources', contextPackage.contextSources ? contextPackage.contextSources.length : 0, { practiceArea: practiceArea || 'unknown' });

        let aiTraceId = null;
        try {
            aiTraceId = await saveCclAiTrace({
                matterId, trackingId, aiStatus: 'complete', model: DEPLOYMENT, durationMs,
                temperature: chatOptions.temperature,
                systemPrompt: SYSTEM_PROMPT, userPrompt: contextPackage.userPrompt, userPromptLength: contextPackage.userPrompt.length,
                aiOutputJson: aiFields, generatedFieldCount: Object.keys(stripEmpty(aiFields)).length,
                confidence: 'full', dataSourcesJson: contextPackage.contextSources,
                contextFieldsJson: contextPackage.debugContext.contextFields, contextSnippetsJson: contextPackage.debugContext.snippets,
                createdBy: actor,
            });
        } catch (err) {
            console.warn('[CCL-AI] Trace persist failed:', err.message);
        }

        return {
            ok: true,
            fields: aiFields,
            confidence: 'full',
            model: DEPLOYMENT,
            durationMs,
            source: 'ai',
            dataSources: contextPackage.contextSources,
            contextSummary: `Used ${contextPackage.contextSources.length} data source(s): ${contextPackage.contextSources.join(', ')}`,
            userPrompt: contextPackage.userPrompt,
            systemPrompt: SYSTEM_PROMPT,
            promptVersion: contextPackage.promptVersion,
            aiTraceId,
            debug: {
                trackingId,
                deployment: DEPLOYMENT,
                aiStatus: 'complete',
                options: chatOptions,
                userPromptLength: contextPackage.userPrompt.length,
                generatedFieldCount: Object.keys(stripEmpty(aiFields)).length,
                context: contextPackage.debugContext,
            },
        };
    } catch (err) {
        const durationMs = Date.now() - startMs;
        console.error(`[CCL-AI] Fill failed (trackingId: ${trackingId}):`, err.message);
        trackException(err, {
            operation: 'CCL.AiFill',
            trackingId,
            matterId: String(matterId),
            practiceArea: practiceArea || 'unknown',
        });
        trackEvent('CCL.AiFill.Failed', {
            trackingId, matterId: String(matterId), error: err.message, durationMs: String(durationMs),
        });

        const paKey = normalisePracticeArea(practiceArea);
        const defaults = PRACTICE_AREA_DEFAULTS[paKey] || PRACTICE_AREA_DEFAULTS['commercial'];
        const fallbackReason = formatFallbackReason(err.message);

        let aiTraceId = null;
        try {
            aiTraceId = await saveCclAiTrace({
                matterId, trackingId, aiStatus: 'fallback', model: 'none', durationMs,
                temperature: chatOptions.temperature,
                systemPrompt: SYSTEM_PROMPT, confidence: 'fallback',
                fallbackReason, errorMessage: err.message,
                createdBy: actor,
            });
        } catch (err2) {
            console.warn('[CCL-AI] Trace persist failed:', err2.message);
        }

        return {
            ok: true,
            fields: defaults,
            confidence: 'fallback',
            model: 'none',
            durationMs,
            source: 'defaults',
            fallbackReason,
            dataSources: [],
            contextSummary: 'AI unavailable — using practice area defaults only',
            userPrompt: '',
            systemPrompt: SYSTEM_PROMPT,
            promptVersion: CCL_PROMPT_VERSION,
            aiTraceId,
            debug: {
                trackingId,
                deployment: DEPLOYMENT,
                aiStatus: 'fallback',
                options: chatOptions,
                userPromptLength: 0,
                generatedFieldCount: 0,
                error: fallbackReason,
                context: {
                    sourceCount: 0,
                    sources: [],
                    snippets: {},
                    contextFields: {
                        practiceArea: practiceArea || '',
                        clientName: clientName || '',
                        opponent: opponent || '',
                    },
                },
            },
        };
    }
}

// ─── POST /api/ccl-ai/fill ─────────────────────────────────────────────────
router.post('/fill', async (req, res) => {
    const {
        matterId, instructionRef, practiceArea, description, clientName,
        opponent, enquiryNotes, handlerName, handlerRole, handlerRate,
    } = req.body || {};

    if (!matterId) {
        return res.status(400).json({ error: 'matterId is required' });
    }

    const actor = resolveRequestActor(req);
    try {
        const result = await runCclAiFill({
            matterId,
            instructionRef,
            practiceArea,
            description,
            clientName,
            opponent,
            enquiryNotes,
            handlerName,
            handlerRole,
            handlerRate,
        }, actor);
        return res.json(result);
    } catch (err) {
        console.error('[CCL-AI] Fill route failed:', err.message);
        trackException(err, { operation: 'CCL.AiFill.Route', matterId: String(matterId) });
        return res.status(500).json({ error: 'Failed to generate AI fields' });
    }
});

// ─── POST /api/ccl-ai/fill-stream (SSE) ────────────────────────────────────
// Streams AI-generated CCL fields in real-time via Server-Sent Events.
// Events: phase, field, complete, error
router.post('/fill-stream', async (req, res) => {
    const {
        matterId, instructionRef, practiceArea, description, clientName,
        opponent, enquiryNotes, handlerName, handlerRole, handlerRate,
    } = req.body || {};

    if (!matterId) {
        return res.status(400).json({ error: 'matterId is required' });
    }

    // SSE headers
    res.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
        'X-Accel-Buffering': 'no',
    });

    const send = (event, data) => {
        res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
    };

    const trackingId = Math.random().toString(36).slice(2, 10);
    const startMs = Date.now();
    const actor = resolveRequestActor(req);
    const chatOptions = { temperature: 0.2 };

    trackEvent('CCL.AiFillStream.Started', {
        trackingId, matterId: String(matterId), practiceArea: practiceArea || 'unknown', deployment: DEPLOYMENT,
    });

    try {
        // Phase 1: Gather context
        send('phase', { phase: 'gathering-context', message: 'Gathering matter context…' });

        const dbContext = await gatherFullContext(matterId, instructionRef);

        const fullContext = {
            practiceArea: practiceArea || dbContext.areaOfWork || '',
            typeOfWork: dbContext.typeOfWork || '',
            description,
            clientName,
            opponent,
            handlerName,
            handlerRole,
            handlerRate,
            clientType: dbContext.clientType || '',
            clientGender: dbContext.clientGender || '',
            company: dbContext.company || '',
            source: dbContext.source || '',
            enquiryValue: dbContext.enquiryValue || '',
            instructionStage: dbContext.instructionStage || '',
            initialCallNotes: dbContext.initialCallNotes || '',
            enquiryNotes: enquiryNotes || dbContext.enquiryNotes || '',
            instructionNotes: dbContext.instructionNotes || '',
            dealServiceDescription: dbContext.dealServiceDescription || '',
            dealAmount: dbContext.dealAmount || '',
            dealPitchedBy: dbContext.dealPitchedBy || '',
            pitchEmailBody: dbContext.pitchEmailBody || '',
            pitchServiceDescription: dbContext.pitchServiceDescription || '',
            pitchAmount: dbContext.pitchAmount || '',
            pitchNotes: dbContext.pitchNotes || '',
            callTranscripts: dbContext.callTranscripts || '',
        };

        const userPrompt = buildUserPrompt(fullContext);
        const contextSources = summariseContextSources(dbContext);
        const debugContext = buildDebugContext(fullContext, contextSources);

        send('phase', {
            phase: 'calling-ai',
            message: `Generating fields from ${contextSources.length} source(s)…`,
            dataSources: contextSources,
        });

        // Phase 2: Stream AI tokens and emit parsed fields incrementally
        let jsonBuffer = '';
        const emittedKeys = new Set();
        let fieldCount = 0;

        const stream = chatCompletionStream(SYSTEM_PROMPT, userPrompt, chatOptions);

        for await (const chunk of await stream) {
            jsonBuffer += chunk;

            // Try to extract newly completed fields from the accumulating JSON
            try {
                const tryParse = jsonBuffer.replace(/,\s*$/, '');
                const closedJson = tryParse.endsWith('}') ? tryParse : tryParse + '}';
                const partial = JSON.parse(closedJson);

                for (const [key, value] of Object.entries(partial)) {
                    if (key.startsWith('_')) continue;
                    if (typeof value === 'string' && value.length > 0 && !emittedKeys.has(key)) {
                        emittedKeys.add(key);
                        fieldCount++;
                        send('field', { key, value, index: fieldCount });
                    }
                }
            } catch {
                // Buffer not yet parseable — continue accumulating
            }
        }

        // Final parse of complete JSON
        let aiFields = {};
        try {
            aiFields = JSON.parse(jsonBuffer);
        } catch {
            aiFields = {};
            // Emit any fields we may have missed
            try {
                const cleaned = jsonBuffer.replace(/,\s*$/, '');
                aiFields = JSON.parse(cleaned.endsWith('}') ? cleaned : cleaned + '}');
            } catch {
                aiFields = { _parseError: true };
            }
        }

        // Emit any remaining fields not yet sent
        for (const [key, value] of Object.entries(aiFields)) {
            if (key.startsWith('_')) continue;
            if (typeof value === 'string' && value.length > 0 && !emittedKeys.has(key)) {
                emittedKeys.add(key);
                fieldCount++;
                send('field', { key, value, index: fieldCount });
            }
        }

        const durationMs = Date.now() - startMs;
        const strippedFields = stripEmpty(aiFields);

        // Validate core fields
        const expectedKeys = ['insert_current_position_and_scope_of_retainer', 'next_steps', 'charges_estimate_paragraph'];
        const hasCore = expectedKeys.every(k => strippedFields[k] && strippedFields[k].length > 10);
        const confidence = hasCore ? 'full' : (Object.keys(strippedFields).length > 0 ? 'partial' : 'fallback');

        // If partial, merge with defaults
        let finalFields = strippedFields;
        if (confidence !== 'full') {
            const paKey = normalisePracticeArea(practiceArea);
            const defaults = PRACTICE_AREA_DEFAULTS[paKey] || PRACTICE_AREA_DEFAULTS['commercial'];
            finalFields = { ...defaults, ...strippedFields };
        }

        // Telemetry
        trackEvent('CCL.AiFillStream.Completed', {
            trackingId, matterId: String(matterId), durationMs: String(durationMs),
            fieldCount: String(fieldCount), confidence,
        });
        trackMetric('CCL.AiFillStream.Duration', durationMs, { practiceArea: practiceArea || 'unknown' });

        // Persist trace (non-blocking)
        saveCclAiTrace({
            matterId, trackingId, aiStatus: confidence, model: DEPLOYMENT, durationMs,
            temperature: chatOptions.temperature,
            systemPrompt: SYSTEM_PROMPT, userPrompt, userPromptLength: userPrompt.length,
            aiOutputJson: strippedFields, generatedFieldCount: fieldCount,
            confidence, dataSourcesJson: contextSources,
            contextFieldsJson: debugContext.contextFields, contextSnippetsJson: debugContext.snippets,
            createdBy: actor,
        }).catch(err => console.warn('[CCL-AI] Stream trace persist failed:', err.message));

        // Send completion event with full metadata
        send('complete', {
            ok: true,
            fields: finalFields,
            confidence,
            model: DEPLOYMENT,
            durationMs,
            source: confidence === 'full' ? 'ai' : (confidence === 'partial' ? 'ai+defaults' : 'defaults'),
            dataSources: contextSources,
            contextSummary: `Used ${contextSources.length} data source(s): ${contextSources.join(', ')}`,
            userPrompt,
            systemPrompt: SYSTEM_PROMPT,
            debug: {
                trackingId,
                deployment: DEPLOYMENT,
                aiStatus: confidence,
                options: chatOptions,
                userPromptLength: userPrompt.length,
                generatedFieldCount: fieldCount,
                context: debugContext,
            },
        });

        res.end();

    } catch (err) {
        const durationMs = Date.now() - startMs;
        console.error(`[CCL-AI] Stream fill failed (trackingId: ${trackingId}):`, err.message);
        trackException(err, { operation: 'CCL.AiFillStream', trackingId, matterId: String(matterId) });
        trackEvent('CCL.AiFillStream.Failed', {
            trackingId, matterId: String(matterId), error: err.message, durationMs: String(durationMs),
        });

        // Fall back to practice area defaults
        const paKey = normalisePracticeArea(practiceArea);
        const defaults = PRACTICE_AREA_DEFAULTS[paKey] || PRACTICE_AREA_DEFAULTS['commercial'];
        const fallbackReason = formatFallbackReason(err.message);

        send('error', { message: fallbackReason, fields: defaults, confidence: 'fallback' });
        res.end();
    }
});

// ─── POST /api/ccl-ai/feedback ──────────────────────────────────────────────
router.post('/feedback', async (req, res) => {
    const { matterId, rating, comment, fieldKey, timestamp } = req.body || {};

    if (!matterId || !rating) {
        return res.status(400).json({ error: 'matterId and rating are required' });
    }

    const allowed = ['up', 'down', 'flag'];
    if (!allowed.includes(rating)) {
        return res.status(400).json({ error: `rating must be one of: ${allowed.join(', ')}` });
    }

    try {
        const user = req.headers['x-user-email'] || req.headers['x-ms-client-principal-name'] || 'unknown';

        // Log to Application Insights as structured event
        trackEvent('CCL.AiFill.Feedback', {
            matterId: String(matterId),
            rating,
            comment: comment || '',
            fieldKey: fieldKey || 'overall',
            timestamp: timestamp || new Date().toISOString(),
            user,
        });

        console.log(`[CCL-AI] Feedback: ${rating} for matter ${matterId}${fieldKey ? ` (field: ${fieldKey})` : ''}${comment ? ` — "${comment}"` : ''}`);

        return res.json({ ok: true, recorded: true });
    } catch (err) {
        console.error('[CCL-AI] Feedback recording failed:', err.message);
        trackException(err, { operation: 'CCL.AiFill.Feedback', matterId: String(matterId) });
        return res.status(500).json({ error: 'Failed to record feedback' });
    }
});

// ─── GET /api/ccl-ai/practice-defaults/:area ───────────────────────────────
router.get('/practice-defaults/:area', (req, res) => {
    const paKey = normalisePracticeArea(req.params.area);
    const defaults = PRACTICE_AREA_DEFAULTS[paKey];
    if (!defaults) {
        return res.status(404).json({ error: `No defaults for practice area: ${req.params.area}` });
    }
    return res.json({ ok: true, fields: defaults, practiceArea: paKey });
});

// ─── POST /api/ccl-ai/context-preview ──────────────────────────────────────
// Dry-run: gathers all context data without calling AI or saving a trace.
// Shows the user what data would be fed into the prompt before committing.
router.post('/context-preview', async (req, res) => {
    const { matterId, instructionRef, practiceArea, description, clientName,
        opponent, enquiryNotes, handlerName, handlerRole, handlerRate } = req.body || {};

    if (!matterId) {
        return res.status(400).json({ error: 'matterId is required' });
    }

    try {
        const preview = await previewCclContext({
            matterId,
            instructionRef,
            practiceArea,
            description,
            clientName,
            opponent,
            enquiryNotes,
            handlerName,
            handlerRole,
            handlerRate,
        });

        return res.json(preview);
    } catch (err) {
        console.error('[CCL-AI] Context preview failed:', err.message);
        trackException(err, { operation: 'CCL.AiFill.ContextPreview', matterId: String(matterId) });
        return res.status(500).json({ error: 'Failed to gather context' });
    }
});

// ─── Helpers ───────────────────────────────────────────────────────────────
function normalisePracticeArea(raw) {
    if (!raw) return 'commercial';
    const lower = raw.toLowerCase().replace(/[^a-z\s-]/g, '').trim();

    if (lower.includes('property') || lower.includes('conveyancing') || lower.includes('real estate')) return 'property';
    if (lower.includes('employment') || lower.includes('hr') || lower.includes('workforce')) return 'employment';
    if (lower.includes('construction') || lower.includes('building')) return 'construction';
    if (lower.includes('dispute') || lower.includes('litigation') || lower.includes('civil')) return 'dispute-resolution';
    if (lower.includes('commercial') || lower.includes('contract') || lower.includes('company') || lower.includes('corporate')) return 'commercial';

    return 'commercial'; // default
}

function stripEmpty(obj) {
    if (!obj || typeof obj !== 'object') return {};
    const result = {};
    for (const [k, v] of Object.entries(obj)) {
        if (k.startsWith('_')) continue;
        if (typeof v === 'string' && v.trim().length > 0) {
            result[k] = v;
        }
    }
    return result;
}

// ─── POST /api/ccl-ai/pressure-test ─────────────────────────────────────────
// After AI generation completes, the frontend calls this to verify output
// confidence. Gathers extended evidence (emails, transcripts, documents,
// pitch content) and asks a second AI pass to score each generated field
// on a 0-10 confidence scale. Fields ≤7 are flagged for Fee Earner review.

const PRESSURE_TEST_SYSTEM_PROMPT = `You are a senior legal quality assurance reviewer at Helix Law, a UK law firm.

You have been given:
1. A set of AI-generated Client Care Letter (CCL) intake fields
2. All available source data: pitch emails, inbound/outbound client emails, call transcripts, document listings, deal data, enquiry notes, and instruction notes

Your task is to VERIFY each generated field against the source data and score your confidence that the field is ACCURATE and APPROPRIATE for this specific matter.

SCORING RULES:
- Score 0-10 for each field
- 10 = perfectly matches source data, no doubt
- 8-9 = strongly supported by evidence, minor wording preference only
- 7 = mostly correct but some aspect is uncertain or could be wrong
- 6 = plausible but weak evidence; may be generic rather than specific to this matter
- 5 or below = likely hallucinated, contradicts evidence, or no supporting data found
- If a field references a specific £ amount, check it matches deal/pitch amounts EXACTLY
- If a field describes the client's situation, check it matches call notes/emails
- If a field names a document the client needs, check it's relevant to the practice area

For each field, provide:
- "score": integer 0-10
- "reason": 1-2 sentences explaining what evidence supports or contradicts the value
- "flag": boolean — true if score ≤ 7 (Fee Earner must check)

Respond with ONLY a JSON object where each key matches the field name, containing {score, reason, flag}. No markdown, no preamble.`;

function buildPressureTestUserPrompt(generatedFields, evidencePackage) {
    const parts = [];

    parts.push('=== GENERATED CCL FIELDS (to verify) ===');
    for (const [key, value] of Object.entries(generatedFields)) {
        if (key.startsWith('_')) continue;
        parts.push(`${key}: ${value}`);
    }

    parts.push('\n=== SOURCE EVIDENCE ===');

    if (evidencePackage.pitchContent) {
        parts.push('\n--- PITCH EMAIL BODY ---');
        parts.push(evidencePackage.pitchContent.substring(0, 3000));
    }
    if (evidencePackage.pitchServiceDescription) {
        parts.push(`\nPitch Service Description: ${evidencePackage.pitchServiceDescription}`);
    }
    if (evidencePackage.pitchAmount) {
        parts.push(`Pitch Amount: £${evidencePackage.pitchAmount}`);
    }
    if (evidencePackage.dealAmount) {
        parts.push(`Deal Amount: £${evidencePackage.dealAmount}`);
    }
    if (evidencePackage.dealServiceDescription) {
        parts.push(`Deal Service Description: ${evidencePackage.dealServiceDescription}`);
    }

    if (evidencePackage.initialCallNotes) {
        parts.push('\n--- INITIAL CALL NOTES ---');
        parts.push(evidencePackage.initialCallNotes.substring(0, 3000));
    }
    if (evidencePackage.enquiryNotes) {
        parts.push('\n--- ENQUIRY NOTES ---');
        parts.push(evidencePackage.enquiryNotes.substring(0, 2000));
    }
    if (evidencePackage.instructionNotes) {
        parts.push('\n--- INSTRUCTION NOTES ---');
        parts.push(evidencePackage.instructionNotes.substring(0, 2000));
    }

    if (evidencePackage.emailsIn && evidencePackage.emailsIn.length > 0) {
        parts.push('\n--- INBOUND EMAILS (from client) ---');
        for (const email of evidencePackage.emailsIn.slice(0, 5)) {
            parts.push(`[${email.date}] Subject: ${email.subject}`);
            parts.push(email.body.substring(0, 1500));
            parts.push('---');
        }
    }

    if (evidencePackage.emailsOut && evidencePackage.emailsOut.length > 0) {
        parts.push('\n--- OUTBOUND EMAILS (to client) ---');
        for (const email of evidencePackage.emailsOut.slice(0, 5)) {
            parts.push(`[${email.date}] Subject: ${email.subject}`);
            parts.push(email.body.substring(0, 1500));
            parts.push('---');
        }
    }

    if (evidencePackage.callTranscripts && evidencePackage.callTranscripts.length > 0) {
        parts.push('\n--- CALL TRANSCRIPTS ---');
        for (const call of evidencePackage.callTranscripts.slice(0, 5)) {
            parts.push(`[${call.date}] ${call.direction || ''} ${call.duration || ''}`);
            if (call.note) parts.push(`Notes: ${call.note}`);
            if (call.transcription) parts.push(`Transcript: ${call.transcription.substring(0, 1500)}`);
            parts.push('---');
        }
    }

    if (evidencePackage.documents && evidencePackage.documents.length > 0) {
        parts.push('\n--- DOCUMENTS ON FILE ---');
        for (const doc of evidencePackage.documents.slice(0, 20)) {
            parts.push(`- ${doc.name} (${doc.type || 'unknown type'}, ${doc.date || 'no date'})`);
        }
    }

    if (evidencePackage.practiceArea) {
        parts.push(`\nPractice Area: ${evidencePackage.practiceArea}`);
    }
    if (evidencePackage.clientName) {
        parts.push(`Client Name: ${evidencePackage.clientName}`);
    }

    parts.push('\n=== INSTRUCTIONS ===');
    parts.push('Score every generated field above. Flag any field scoring 7 or below. Pay special attention to:');
    parts.push('- £ amounts matching deal/pitch data exactly');
    parts.push('- Scope of retainer matching what was actually discussed');
    parts.push('- Document requests being specific to this matter, not generic');
    parts.push('- Timescales being realistic for this practice area and complexity');

    return parts.join('\n');
}

async function gatherVerificationEvidence(matterId, instructionRef, feeEarnerEmail, prospectEmail, phone) {
    const base = getInternalBase();
    const evidence = {};

    // Gather emails (inbound + outbound, up to 10 total split by direction)
    if (feeEarnerEmail && prospectEmail) {
        try {
            const resp = await fetch(`${base}/api/searchInbox`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ feeEarnerEmail, prospectEmail, maxResults: 20 }),
            });
            if (resp.ok) {
                const data = await resp.json();
                const emails = data.emails || [];
                const emailsIn = [];
                const emailsOut = [];
                for (const e of emails) {
                    const fromAddr = (e.from || '').toLowerCase();
                    const prospectLower = prospectEmail.toLowerCase();
                    const entry = {
                        date: e.receivedDateTime ? new Date(e.receivedDateTime).toLocaleDateString('en-GB') : '',
                        subject: e.subject || '',
                        body: e.bodyText || stripHtmlForVerification(e.bodyHtml) || e.bodyPreview || '',
                    };
                    if (fromAddr === prospectLower) {
                        if (emailsIn.length < 5) emailsIn.push(entry);
                    } else {
                        if (emailsOut.length < 5) emailsOut.push(entry);
                    }
                }
                evidence.emailsIn = emailsIn;
                evidence.emailsOut = emailsOut;
            }
        } catch (err) {
            console.warn('[CCL-AI] Pressure test email fetch failed:', err.message);
        }
    }

    // Gather call transcripts (up to 5)
    if (phone) {
        try {
            const resp = await fetch(`${base}/api/callrailCalls`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ phoneNumber: phone, maxResults: 5 }),
            });
            if (resp.ok) {
                const data = await resp.json();
                const calls = Array.isArray(data) ? data : data.calls || [];
                evidence.callTranscripts = calls.filter(c => c.transcription || c.note).slice(0, 5).map(c => ({
                    date: c.startTime ? new Date(c.startTime).toLocaleDateString('en-GB') : '',
                    direction: c.direction || '',
                    duration: c.duration ? `${Math.round(c.duration / 60)}min` : '',
                    note: c.note || '',
                    transcription: c.transcription || '',
                }));
            }
        } catch (err) {
            console.warn('[CCL-AI] Pressure test CallRail fetch failed:', err.message);
        }
    }

    // Gather document list (if we have an instructionRef)
    if (instructionRef) {
        try {
            const resp = await fetch(`${base}/api/documents/${encodeURIComponent(instructionRef)}`);
            if (resp.ok) {
                const data = await resp.json();
                const docs = Array.isArray(data) ? data : data.documents || [];
                evidence.documents = docs.slice(0, 20).map(d => ({
                    name: d.name || d.fileName || d.originalName || 'Unknown',
                    type: d.contentType || d.type || '',
                    date: d.uploadedAt || d.createdAt || '',
                }));
            }
        } catch (err) {
            console.warn('[CCL-AI] Pressure test document listing failed:', err.message);
        }
    }

    return evidence;
}

function stripHtmlForVerification(html) {
    if (!html) return '';
    return html
        .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
        .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
        .replace(/<[^>]+>/g, ' ')
        .replace(/&nbsp;/gi, ' ')
        .replace(/&amp;/gi, '&')
        .replace(/&lt;/gi, '<')
        .replace(/&gt;/gi, '>')
        .replace(/&quot;/gi, '"')
        .replace(/\s+/g, ' ')
        .trim();
}

router.post('/pressure-test', async (req, res) => {
    const {
        matterId, instructionRef, generatedFields, practiceArea, clientName,
        feeEarnerEmail, prospectEmail,
    } = req.body || {};

    if (!matterId || !generatedFields || typeof generatedFields !== 'object') {
        return res.status(400).json({ error: 'matterId and generatedFields are required' });
    }

    const trackingId = Math.random().toString(36).slice(2, 10);
    const startMs = Date.now();
    const actor = resolveRequestActor(req);

    trackEvent('CCL.PressureTest.Started', {
        trackingId, matterId: String(matterId), fieldCount: String(Object.keys(generatedFields).length),
    });

    try {
        // Phase 1: Gather the original context (reuse gatherFullContext)
        const dbContext = await gatherFullContext(matterId, instructionRef);

        // Phase 2: Gather extended verification evidence (emails, transcripts, documents)
        const resolvedFeeEarnerEmail = feeEarnerEmail || dbContext.feeEarnerEmail || '';
        const resolvedProspectEmail = prospectEmail || dbContext.prospectEmail || '';
        const resolvedPhone = dbContext.phone || '';

        const externalEvidence = await gatherVerificationEvidence(
            matterId, instructionRef, resolvedFeeEarnerEmail, resolvedProspectEmail, resolvedPhone,
        );

        // Phase 3: Build the verification evidence package
        const evidencePackage = {
            // From original context
            pitchContent: dbContext.pitchEmailBody || '',
            pitchServiceDescription: dbContext.pitchServiceDescription || '',
            pitchAmount: dbContext.pitchAmount || '',
            dealAmount: dbContext.dealAmount || '',
            dealServiceDescription: dbContext.dealServiceDescription || '',
            initialCallNotes: dbContext.initialCallNotes || '',
            enquiryNotes: dbContext.enquiryNotes || '',
            instructionNotes: dbContext.instructionNotes || '',
            practiceArea: practiceArea || dbContext.areaOfWork || '',
            clientName: clientName || '',
            // From extended evidence
            ...externalEvidence,
        };

        const dataSources = [];
        if (evidencePackage.pitchContent) dataSources.push('Pitch email');
        if (evidencePackage.dealAmount) dataSources.push('Deal data');
        if (evidencePackage.initialCallNotes) dataSources.push('Initial call notes');
        if (evidencePackage.enquiryNotes) dataSources.push('Enquiry notes');
        if (evidencePackage.instructionNotes) dataSources.push('Instruction notes');
        if (externalEvidence.emailsIn?.length) dataSources.push(`${externalEvidence.emailsIn.length} inbound emails`);
        if (externalEvidence.emailsOut?.length) dataSources.push(`${externalEvidence.emailsOut.length} outbound emails`);
        if (externalEvidence.callTranscripts?.length) dataSources.push(`${externalEvidence.callTranscripts.length} call transcripts`);
        if (externalEvidence.documents?.length) dataSources.push(`${externalEvidence.documents.length} documents`);

        // Phase 4: Call AI for verification scoring
        const userPrompt = buildPressureTestUserPrompt(generatedFields, evidencePackage);

        const verificationResult = await chatCompletion(
            PRESSURE_TEST_SYSTEM_PROMPT,
            userPrompt,
            { temperature: 0.1 },
        );

        const durationMs = Date.now() - startMs;

        // Normalise the result — ensure every field has score/reason/flag
        const fieldScores = {};
        let flaggedCount = 0;
        for (const [key, value] of Object.entries(generatedFields)) {
            if (key.startsWith('_')) continue;
            const aiScore = verificationResult[key];
            if (aiScore && typeof aiScore === 'object') {
                const score = typeof aiScore.score === 'number' ? aiScore.score : 5;
                const flag = score <= 7;
                fieldScores[key] = {
                    score,
                    reason: String(aiScore.reason || 'No reason provided'),
                    flag,
                };
                if (flag) flaggedCount++;
            } else {
                // AI didn't score this field — flag it by default
                fieldScores[key] = {
                    score: 5,
                    reason: 'Verification AI did not return a score for this field — requires manual review',
                    flag: true,
                };
                flaggedCount++;
            }
        }

        trackEvent('CCL.PressureTest.Completed', {
            trackingId, matterId: String(matterId), durationMs: String(durationMs),
            fieldCount: String(Object.keys(fieldScores).length),
            flaggedCount: String(flaggedCount),
            dataSourceCount: String(dataSources.length),
        });
        trackMetric('CCL.PressureTest.Duration', durationMs, { matterId: String(matterId) });

        return res.json({
            ok: true,
            fieldScores,
            flaggedCount,
            totalFields: Object.keys(fieldScores).length,
            dataSources,
            durationMs,
            trackingId,
        });

    } catch (err) {
        const durationMs = Date.now() - startMs;
        console.error(`[CCL-AI] Pressure test failed (trackingId: ${trackingId}):`, err.message);
        trackException(err, { operation: 'CCL.PressureTest', trackingId, matterId: String(matterId) });
        trackEvent('CCL.PressureTest.Failed', {
            trackingId, matterId: String(matterId), error: err.message, durationMs: String(durationMs),
        });

        return res.status(500).json({ error: 'Pressure test failed', message: err.message });
    }
});

router.buildCclContextPackage = buildCclContextPackage;
router.previewCclContext = previewCclContext;
router.runCclAiFill = runCclAiFill;
router.CCL_PROMPT_VERSION = CCL_PROMPT_VERSION;

module.exports = router;
