// server/utils/asanaTasks.js
//
// Thin task-level wrappers over Asana's REST API for the Operator Actions
// surface (B1, Phase B). Authentication reuses resolveAsanaAccessToken from
// server/utils/asana.js — same per-user OAuth refresh path the rest of the
// app uses.

const { ASANA_BASE_URL, resolveAsanaAccessToken } = require('./asana');

async function asanaFetch(path, accessToken, init = {}) {
  const headers = {
    Authorization: `Bearer ${accessToken}`,
    'Content-Type': 'application/json',
    Accept: 'application/json',
    ...(init.headers || {}),
  };
  const res = await fetch(`${ASANA_BASE_URL}${path}`, { ...init, headers });
  let body = null;
  try {
    body = await res.json();
  } catch {
    body = null;
  }
  if (!res.ok) {
    const message = body?.errors?.[0]?.message || body?.message || `Asana ${res.status}`;
    const err = new Error(message);
    err.status = res.status;
    err.body = body;
    throw err;
  }
  return body;
}

// Add a comment (story) to an Asana task.
// `text` is plain text. Asana also accepts html_text but plain is sufficient
// for posting summaries / JSON snippets and avoids HTML escaping concerns.
async function addCommentToTask({ accessToken, taskGid, text }) {
  if (!taskGid) throw new Error('taskGid is required');
  if (!text || !String(text).trim()) throw new Error('text is required');
  const body = { data: { text: String(text) } };
  const result = await asanaFetch(
    `/tasks/${encodeURIComponent(taskGid)}/stories`,
    accessToken,
    { method: 'POST', body: JSON.stringify(body) },
  );
  return result?.data || null;
}

// Create a new Asana task in a section. Workspace is required; we infer it
// from the configured ASANA_WORKSPACE_ID by default but callers may override.
async function createTaskInSection({
  accessToken,
  sectionGid,
  workspaceGid,
  name,
  notes,
}) {
  if (!sectionGid) throw new Error('sectionGid is required');
  if (!name || !String(name).trim()) throw new Error('name is required');
  const workspace = workspaceGid || process.env.ASANA_WORKSPACE_ID || '1203336123398249';
  const data = {
    name: String(name).slice(0, 200),
    workspace,
    memberships: [{ section: sectionGid }],
  };
  if (notes && String(notes).trim()) {
    // Asana caps notes at ~65k chars. We hard-cap at 60k to leave headroom
    // for any prefix the caller adds (e.g. a "Generated by Helix" footer).
    data.notes = String(notes).slice(0, 60000);
  }
  const result = await asanaFetch(
    `/tasks`,
    accessToken,
    { method: 'POST', body: JSON.stringify({ data }) },
  );
  return result?.data || null;
}

module.exports = {
  resolveAsanaAccessToken,
  addCommentToTask,
  createTaskInSection,
};
